apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-base
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: php-apache
          image: cheikht/apache_ct
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_NAME
              value: fil_rouge
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
      volumes:
        - name: app-volume
          emptyDir: {}